export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
export const ORDER_BY_ALPHABET = 'ORDER_BY_ALPHABET';
export const ORDER_BY_RATING = 'ORDER_BY_RATING';